- name: Unir el nodo worker al clúster K3s
  hosts: k3s_worker01
  become: true
  vars:
    k3s_server_url: "https://100.85.236.20:6443"
    local_token_file: "/tmp/k3s_token.txt"
    remote_token_file: "/tmp/node-token"

  tasks:
    - name: Leer token desde el host local
      set_fact:
        k3s_token: "{{ lookup('file', local_token_file) }}"
      delegate_to: localhost
      run_once: true

    - name: Copiar token al nodo worker
      copy:
        dest: "{{ remote_token_file }}"
        content: "{{ k3s_token }}"

    - name: Instalar K3s como agente
      shell: |
        curl -sfL https://get.k3s.io | \
        K3S_URL={{ k3s_server_url }} \
        K3S_TOKEN=$(cat {{ remote_token_file }}) \
        sh -
      args:
        creates: /usr/local/bin/k3s-agent
