- name: Instalar K3s en el nodo master
  hosts: master
  become: true

  tasks:
    - name: Descargar e instalar K3s
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Esperar a que k3s esté operativo
      shell: kubectl get nodes
      register: k3s_ready
      retries: 5
      delay: 5
      until: k3s_ready.rc == 0

    - name: Obtener token del clúster
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Guardar token en el host local
      copy:
        dest: /tmp/k3s_token.txt
        content: "{{ k3s_token.content | b64decode }}"
      delegate_to: localhost
      run_once: true
