- name: Extraer token K3s del nodo master y guardarlo en el host local
  hosts: master
  become: true
  tasks:
    - name: Leer token desde el nodo master
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Guardar token en el host local
      copy:
        dest: /tmp/k3s_token.txt
        content: "{{ k3s_token.content | b64decode }}"
      delegate_to: localhost
      run_once: true
